name: flutter_marinabung
description: 'MariNabung Application'
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.6.1
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.9.0
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0
  shared_preferences: ^2.5.3
  flutter_dotenv: ^5.2.1
  image_picker: ^1.1.2
  uuid: ^4.5.1
  image_cropper: ^9.1.0
  intl: ^0.20.2
  percent_indicator: ^4.2.5
  flutter_launcher_icons: ^0.14.4
  flutter_local_notifications: ^19.3.0
  timezone: ^0.10.1
  android_alarm_manager_plus: ^4.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - images/
